### ISSUE TITLE
New ids with the same input repeats the saved information from the previous one.

### ISSUE THREAD

**Issue by georgemiler** [pedro-jmanuel/oops#1]
I have the following situation, each page contains a different ID, but if I leave page X, and enter page Y, the data on page X still appear on page Y. I imagine that the cookies or session must be saved by unique ID, so every time you enter a page and leave it, just get it back

**Comment by pedro-jmanuel** [comment]
Hi The situation is being verified. Thanks,

**Comment by pedro-jmanuel** [comment]
You can try the following solution.

Use different keys for Oops instance for different pages.

Page  X 

var config = {
key:"page_x"
}
var x = new Oops(config);

Page  Y 

var config = {
key:"page_y"
}
var y = new Oops(config);
